# Generated by Django 5.0.2 on 2025-04-16 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_banners_alter_category_parents_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='image3',
        ),
        migrations.AddField(
            model_name='banners',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='banners/'),
            preserve_default=False,
        ),
    ]
